# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protos.logging_pb2 as logging__pb2


class LoggingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getLogging = channel.unary_unary(
                '/Logging/getLogging',
                request_serializer=logging__pb2.GetLoggingRequest.SerializeToString,
                response_deserializer=logging__pb2.GetLoggingResponse.FromString,
                )
        self.postLogging = channel.unary_unary(
                '/Logging/postLogging',
                request_serializer=logging__pb2.PostLoggingRequest.SerializeToString,
                response_deserializer=logging__pb2.PostLoggingResponse.FromString,
                )


class LoggingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getLogging(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def postLogging(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoggingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getLogging': grpc.unary_unary_rpc_method_handler(
                    servicer.getLogging,
                    request_deserializer=logging__pb2.GetLoggingRequest.FromString,
                    response_serializer=logging__pb2.GetLoggingResponse.SerializeToString,
            ),
            'postLogging': grpc.unary_unary_rpc_method_handler(
                    servicer.postLogging,
                    request_deserializer=logging__pb2.PostLoggingRequest.FromString,
                    response_serializer=logging__pb2.PostLoggingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Logging', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Logging(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getLogging(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Logging/getLogging',
            logging__pb2.GetLoggingRequest.SerializeToString,
            logging__pb2.GetLoggingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def postLogging(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Logging/postLogging',
            logging__pb2.PostLoggingRequest.SerializeToString,
            logging__pb2.PostLoggingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
